spring.application.name=client-service

server.port=9083


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/system_monitoring
spring.datasource.username=root
spring.datasource.password=insightzz@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never


# =========================================================
# CUSTOM JWT
# =========================================================

jwt.secret=ASsqb11Bh2B52uTCt3G24k+9mjthMjEjcdsockK2W+U=

# ======================================================
# LOGGING
# ======================================================
logging.level.root=INFO
logging.level.com.insightzz=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

# ERROR level explicitly aur stack trace print
logging.level.org.springframework.boot.web.servlet.support=ERROR

